
stacks_private_key = "530d9f61984c888536871c6573073bdfc0058896dc1adfe9a6a10dfacadc209101"
node_host = "stacks-node.Raze.devnet:20443" # eg "127.0.0.1:20443"
# must be added as event_observer in node config:
endpoint = "0.0.0.0:30002"
network = "testnet"
auth_password = "12345"
db_path = "stacks-signer-2.sqlite"
