[project]
name = 'CrowdFund'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.BankDAO]
path = 'contracts/BankDAO.clar'
clarity_version = 2
epoch = 2.5

[contracts.Campaign]
path = 'contracts/Campaign.clar'
clarity_version = 2
epoch = 2.5

[contracts.Creator]
path = 'contracts/Creator.clar'
clarity_version = 2
epoch = 2.5

[contracts.Wallet]
path = 'contracts/Wallet.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
